sudo: required
services: 
  - docker 
before_install: 
  - docker build -t oisinodonnell/docker-react -f Dockerfile.dev . 
script: 
  - docker run oisinodonnell/docker-react npm run test -- --coverage